"""
Comprehensive lender catalog. Every field maps to the new model schema.
req_* fields are HARD requirements (fail = disqualified immediately).
ideal_* fields are SOFT scoring factors.
"""

LENDERS = [
    # ══════════════════════════════════════════════════════════════════
    # TIER: STARTER — Net-30 Vendors (zero credit check, D&B builders)
    # Apply these FIRST. No hard pulls. Every one builds D&B PAYDEX.
    # ══════════════════════════════════════════════════════════════════
    {
        "name": "Uline",
        "category": "net30",
        "tier": "starter",
        "website": "https://www.uline.com",
        "application_url": "https://www.uline.com/BL_8/Open-Account",
        "product_type": "Net-30 Trade Account",
        "credit_limit_min": 500, "credit_limit_max": 50000,
        "payment_terms": "net30",
        "req_min_months_in_business": 0,
        "req_min_annual_revenue": 0,
        "req_min_personal_credit": 0,
        "req_ein": True,
        "req_business_checking": False,
        "ideal_min_months": 0,
        "hard_pull": False,
        "requires_personal_guarantee": False,
        "reports_to_dnb": True, "reports_to_experian_biz": True, "reports_to_equifax_biz": False,
        "automation_script": "uline",
        "approval_time": "Instant - 2 business days",
        "description": "Industrial & shipping supplies. Reports to D&B + Experian Business monthly. One of the most powerful tradeline builders for new businesses.",
        "notes": "Place a small order after approval (packing tape, boxes etc.) to activate the account and start reporting.",
    },
    {
        "name": "Grainger",
        "category": "net30",
        "tier": "starter",
        "website": "https://www.grainger.com",
        "application_url": "https://www.grainger.com/content/replenishment-open-account",
        "product_type": "Net-30 Trade Account",
        "credit_limit_min": 1000, "credit_limit_max": 100000,
        "payment_terms": "net30",
        "req_min_months_in_business": 0,
        "req_min_annual_revenue": 0,
        "req_min_personal_credit": 0,
        "req_ein": True,
        "hard_pull": False,
        "requires_personal_guarantee": False,
        "reports_to_dnb": True, "reports_to_experian_biz": True, "reports_to_equifax_biz": True,
        "automation_script": "generic",
        "approval_time": "1-3 business days",
        "description": "Industrial MRO supplies. Reports to ALL 3 major business bureaus — D&B, Experian, and Equifax. Extremely valuable tradeline.",
    },
    {
        "name": "Quill",
        "category": "net30",
        "tier": "starter",
        "website": "https://www.quill.com",
        "application_url": "https://www.quill.com/shop/credit.html",
        "product_type": "Net-30 Trade Account",
        "credit_limit_min": 500, "credit_limit_max": 20000,
        "payment_terms": "net30",
        "req_min_months_in_business": 0,
        "req_min_annual_revenue": 0,
        "req_min_personal_credit": 0,
        "req_ein": True,
        "hard_pull": False,
        "requires_personal_guarantee": False,
        "reports_to_dnb": True, "reports_to_experian_biz": False, "reports_to_equifax_biz": False,
        "automation_script": "generic",
        "approval_time": "Instant - 1 day",
        "description": "Office supplies (Staples subsidiary). Super easy approval for brand new EINs. Often approves on day 1.",
    },
    {
        "name": "Summa Office Supplies",
        "category": "net30",
        "tier": "starter",
        "website": "https://www.summaoffice.com",
        "application_url": "https://www.summaoffice.com/open-account/",
        "product_type": "Net-30 Trade Account",
        "credit_limit_min": 100, "credit_limit_max": 5000,
        "payment_terms": "net30",
        "req_min_months_in_business": 0,
        "req_min_annual_revenue": 0,
        "req_min_personal_credit": 0,
        "req_ein": False,
        "hard_pull": False,
        "requires_personal_guarantee": False,
        "reports_to_dnb": True,
        "automation_script": "generic",
        "approval_time": "Same day",
        "description": "Designed specifically as a credit builder. No EIN required. Instant same-day approval. First tradeline for many new businesses.",
    },
    {
        "name": "Crown Office Supplies",
        "category": "net30",
        "tier": "starter",
        "website": "https://www.crownofficysupplies.com",
        "application_url": "https://www.crownofficysupplies.com/account/register",
        "product_type": "Net-30 Trade Account",
        "credit_limit_min": 50, "credit_limit_max": 2500,
        "payment_terms": "net30",
        "req_min_months_in_business": 0,
        "req_min_annual_revenue": 0,
        "req_min_personal_credit": 0,
        "req_ein": False,
        "hard_pull": False,
        "requires_personal_guarantee": False,
        "reports_to_dnb": True,
        "automation_script": "generic",
        "approval_time": "Instant",
        "description": "Easy starter Net-30. Reports monthly to D&B. Perfect for brand new businesses.",
    },
    {
        "name": "The CEO Creative",
        "category": "net30",
        "tier": "starter",
        "website": "https://theceocreative.com",
        "application_url": "https://theceocreative.com/collections/net-30",
        "product_type": "Net-30 Trade Account",
        "credit_limit_min": 50, "credit_limit_max": 2000,
        "payment_terms": "net30",
        "req_min_months_in_business": 0,
        "req_min_annual_revenue": 0,
        "req_min_personal_credit": 0,
        "req_ein": False,
        "hard_pull": False,
        "requires_personal_guarantee": False,
        "reports_to_dnb": True,
        "automation_script": "generic",
        "approval_time": "Instant",
        "description": "Digital products. Instant net-30 approval. Fast D&B reporting. Great first tradeline.",
    },
    {
        "name": "Creative Analytics",
        "category": "net30",
        "tier": "starter",
        "website": "https://www.creativeanalytics.com",
        "application_url": "https://www.creativeanalytics.com/open-an-account/",
        "product_type": "Net-30 Trade Account",
        "credit_limit_min": 100, "credit_limit_max": 5000,
        "payment_terms": "net30",
        "req_min_months_in_business": 0,
        "req_min_annual_revenue": 0,
        "req_min_personal_credit": 0,
        "req_ein": False,
        "hard_pull": False,
        "requires_personal_guarantee": False,
        "reports_to_dnb": True,
        "automation_script": "generic",
        "approval_time": "Same day",
        "description": "Marketing services. Reports to D&B.",
    },
    {
        "name": "Wise Business Plans",
        "category": "net30",
        "tier": "starter",
        "website": "https://wisebusinessplans.com",
        "application_url": "https://wisebusinessplans.com/contact-us/",
        "product_type": "Net-30 Trade Account",
        "credit_limit_min": 100, "credit_limit_max": 5000,
        "payment_terms": "net30",
        "req_min_months_in_business": 0,
        "req_min_annual_revenue": 0,
        "req_min_personal_credit": 0,
        "req_ein": False,
        "hard_pull": False,
        "requires_personal_guarantee": False,
        "reports_to_dnb": True,
        "automation_script": "generic",
        "approval_time": "1-2 days",
        "description": "Business planning services. Net-30 with D&B reporting.",
    },
    {
        "name": "Staples Business Advantage",
        "category": "net30",
        "tier": "established",
        "website": "https://www.staplesadvantage.com",
        "application_url": "https://www.staplesadvantage.com/portal/en_US/login.html",
        "product_type": "Net-30 Trade Account",
        "credit_limit_min": 500, "credit_limit_max": 25000,
        "payment_terms": "net30",
        "req_min_months_in_business": 0,
        "req_min_annual_revenue": 0,
        "req_min_personal_credit": 0,
        "req_ein": True,
        "hard_pull": False,
        "requires_personal_guarantee": False,
        "reports_to_dnb": True,
        "automation_script": "generic",
        "approval_time": "2-5 days",
        "description": "Office supplies Net-30. D&B reporting.",
    },
    {
        "name": "Office Depot Business",
        "category": "net30",
        "tier": "starter",
        "website": "https://business.officedepot.com",
        "application_url": "https://business.officedepot.com/a/jsp/account/openAccountReturning.jsp",
        "product_type": "Net-30 Trade Account",
        "credit_limit_min": 500, "credit_limit_max": 20000,
        "payment_terms": "net30",
        "req_min_months_in_business": 0,
        "req_min_annual_revenue": 0,
        "req_min_personal_credit": 0,
        "req_ein": True,
        "hard_pull": False,
        "requires_personal_guarantee": False,
        "reports_to_dnb": True,
        "automation_script": "generic",
        "approval_time": "1-3 days",
        "description": "Office supplies. Reports to D&B.",
    },
    {
        "name": "Nine to Five Essentials Plus",
        "category": "net30",
        "tier": "starter",
        "website": "https://nineto5essentials.com",
        "application_url": "https://nineto5essentials.com/pages/net-30-account",
        "product_type": "Net-30 Trade Account",
        "credit_limit_min": 100, "credit_limit_max": 5000,
        "payment_terms": "net30",
        "req_min_months_in_business": 0,
        "req_min_annual_revenue": 0,
        "req_min_personal_credit": 0,
        "req_ein": True,
        "hard_pull": False,
        "requires_personal_guarantee": False,
        "reports_to_dnb": False, "reports_to_experian_biz": True, "reports_to_equifax_biz": False,
        "automation_script": "generic",
        "approval_time": "Same day",
        "description": "Office essentials Net-30. No fee. Reports monthly to Experian Business.",
    },
    {
        "name": "Coast to Coast Office Supply",
        "category": "net30",
        "tier": "starter",
        "website": "https://coasttocoastofficesupply.com",
        "application_url": "https://coasttocoastofficesupply.com/pages/net-30",
        "product_type": "Net-30 Trade Account",
        "credit_limit_min": 100, "credit_limit_max": 3000,
        "payment_terms": "net30",
        "req_min_months_in_business": 0,
        "req_min_annual_revenue": 0,
        "req_min_personal_credit": 0,
        "req_ein": True,
        "hard_pull": False,
        "requires_personal_guarantee": False,
        "reports_to_dnb": False, "reports_to_experian_biz": True, "reports_to_equifax_biz": False,
        "automation_script": "generic",
        "approval_time": "Instant",
        "description": "Office supply Net-30. No fee. Select 'Bill My Net-30 Terms Account' at checkout. Reports to Experian.",
    },
    {
        "name": "Office Garner",
        "category": "net30",
        "tier": "starter",
        "website": "https://officegarner.com",
        "application_url": "https://officegarner.com/pages/net30-credit",
        "product_type": "Net-30 Trade Account",
        "credit_limit_min": 200, "credit_limit_max": 5000,
        "payment_terms": "net30",
        "req_min_months_in_business": 1,
        "req_min_annual_revenue": 0,
        "req_min_personal_credit": 0,
        "req_ein": True,
        "hard_pull": False,
        "requires_personal_guarantee": False,
        "reports_to_dnb": False, "reports_to_experian_biz": True, "reports_to_equifax_biz": False,
        "automation_script": "generic",
        "approval_time": "1-2 days",
        "description": "Office products Net-30. $69 one-time setup. Reports to Experian Business. 30+ days in business preferred.",
    },
    {
        "name": "NAMYNOT Inc.",
        "category": "net30",
        "tier": "starter",
        "website": "https://namynot.com",
        "application_url": "https://namynot.com/pages/net-30-account",
        "product_type": "Net-30 Trade Account",
        "credit_limit_min": 500, "credit_limit_max": 10000,
        "payment_terms": "net30",
        "req_min_months_in_business": 0,
        "req_min_annual_revenue": 0,
        "req_min_personal_credit": 0,
        "req_ein": True,
        "hard_pull": False,
        "requires_personal_guarantee": False,
        "reports_to_dnb": False, "reports_to_experian_biz": True, "reports_to_equifax_biz": True,
        "automation_script": "generic",
        "approval_time": "1-2 days",
        "description": "Digital marketing services. Reports to both Experian and Equifax Business. Up to $10K limit. 2-day approval.",
    },
    {
        "name": "JJ Gold International",
        "category": "net30",
        "tier": "starter",
        "website": "https://jjgoldinternational.com",
        "application_url": "https://jjgoldinternational.com/pages/net30",
        "product_type": "Net-30 Trade Account",
        "credit_limit_min": 200, "credit_limit_max": 7500,
        "payment_terms": "net30",
        "req_min_months_in_business": 1,
        "req_min_annual_revenue": 0,
        "req_min_personal_credit": 0,
        "req_ein": True,
        "hard_pull": False,
        "requires_personal_guarantee": False,
        "reports_to_dnb": False, "reports_to_experian_biz": True, "reports_to_equifax_biz": True,
        "automation_script": "generic",
        "approval_time": "1-3 days",
        "description": "Wholesale products Net-30. Reports to Experian + Equifax. Requires EIN + utility bill or bank statement.",
    },
    {
        "name": "GoodNeon",
        "category": "net30",
        "tier": "builder",
        "website": "https://goodneon.com",
        "application_url": "https://goodneon.com/pages/net-30",
        "product_type": "Net-30 Trade Account",
        "credit_limit_min": 500, "credit_limit_max": 5000,
        "payment_terms": "net30",
        "req_min_months_in_business": 0,
        "req_min_annual_revenue": 0,
        "req_min_personal_credit": 0,
        "req_ein": True,
        "req_min_tradelines": 2,
        "hard_pull": False,
        "requires_personal_guarantee": False,
        "reports_to_dnb": False, "reports_to_experian_biz": True, "reports_to_equifax_biz": True,
        "automation_script": "generic",
        "approval_time": "1-2 days",
        "description": "Custom neon signs. Reports to Experian + Equifax. Needs 2 prior net-30 tradelines. $5K revolving limit. No personal check.",
    },
    {
        "name": "Harbor Freight Tools",
        "category": "net30",
        "tier": "starter",
        "website": "https://www.harborfreight.com",
        "application_url": "https://www.harborfreight.com/commercial-credit-account.html",
        "product_type": "Net-30 Commercial Account",
        "credit_limit_min": 500, "credit_limit_max": 10000,
        "payment_terms": "net30",
        "req_min_months_in_business": 0,
        "req_min_annual_revenue": 0,
        "req_min_personal_credit": 0,
        "req_ein": True,
        "hard_pull": False,
        "requires_personal_guarantee": False,
        "reports_to_dnb": False, "reports_to_experian_biz": True, "reports_to_equifax_biz": False,
        "automation_script": "generic",
        "approval_time": "1-3 days",
        "description": "Tools & equipment commercial account. Pay by invoice. Reports to Experian Business.",
    },
    {
        "name": "HD Supply",
        "category": "net30",
        "tier": "builder",
        "website": "https://www.hdsupply.com",
        "application_url": "https://www.hdsupply.com/intershop/web/HDS/HSI-US/en_US/USD/SignIn-Start",
        "product_type": "Net-30 Trade Account",
        "credit_limit_min": 500, "credit_limit_max": 25000,
        "payment_terms": "net30",
        "req_min_months_in_business": 0,
        "req_min_annual_revenue": 0,
        "req_min_personal_credit": 0,
        "req_ein": True,
        "hard_pull": False,
        "requires_personal_guarantee": False,
        "reports_to_dnb": False, "reports_to_experian_biz": True, "reports_to_equifax_biz": False,
        "automation_script": "generic",
        "approval_time": "2-5 days",
        "description": "MRO & facility maintenance. Works alongside Home Depot commercial. Reports to Experian Business.",
    },
    {
        "name": "Newegg Business",
        "category": "net30",
        "tier": "builder",
        "website": "https://www.newegg.com/business",
        "application_url": "https://www.newegg.com/seller/home.aspx",
        "product_type": "Net-30 Trade Account",
        "credit_limit_min": 500, "credit_limit_max": 15000,
        "payment_terms": "net30",
        "req_min_months_in_business": 0,
        "req_min_annual_revenue": 0,
        "req_min_personal_credit": 0,
        "req_ein": True,
        "hard_pull": False,
        "requires_personal_guarantee": False,
        "reports_to_dnb": False, "reports_to_experian_biz": True, "reports_to_equifax_biz": False,
        "automation_script": "generic",
        "approval_time": "2-5 days",
        "description": "Electronics & tech supplies. Two-step: open Newegg Business account first, then apply for Net-30 terms. Reports to Experian.",
    },
    {
        "name": "WEX Fleet Card",
        "category": "fuel_card",
        "tier": "starter",
        "website": "https://www.wexinc.com",
        "application_url": "https://www.wexinc.com/products/fleet-cards/",
        "product_type": "Fleet/Fuel Card",
        "credit_limit_min": 500, "credit_limit_max": 25000,
        "payment_terms": "net30",
        "req_min_months_in_business": 0,
        "req_min_annual_revenue": 0,
        "req_min_personal_credit": 0,
        "req_ein": True,
        "hard_pull": False,
        "requires_personal_guarantee": False,
        "reports_to_dnb": True,
        "automation_script": "generic",
        "approval_time": "1-3 days",
        "description": "Fleet fuel card. No personal guarantee or credit check. D&B reporting.",
    },
    # ══════════════════════════════════════════════════════════════════
    # TIER: BUILDER — Soft-pull cards, fuel, store cards
    # Apply after 3+ net-30 tradelines established
    # ══════════════════════════════════════════════════════════════════
    {
        "name": "Brex Corporate Card",
        "category": "credit_card",
        "tier": "builder",
        "website": "https://www.brex.com",
        "application_url": "https://www.brex.com/signup",
        "product_type": "Corporate Charge Card",
        "credit_limit_min": 5000, "credit_limit_max": 5000000,
        "payment_terms": "monthly",
        "req_min_months_in_business": 0,
        "req_min_annual_revenue": 0,
        "req_min_personal_credit": 0,
        "req_min_bank_balance": 1000,
        "req_ein": True,
        "req_business_checking": True,
        "ideal_bank_balance": 10000,
        "hard_pull": False,
        "requires_personal_guarantee": False,
        "reports_to_dnb": True, "reports_to_experian_biz": True,
        "automation_script": "brex",
        "approval_time": "1-3 days",
        "description": "No personal guarantee, no credit check. Based on bank balance. Limit ~10-25% of balance. Best startup card.",
        "notes": "Connect bank account after signup. Keep $5k+ balance for best limit.",
    },
    {
        "name": "Ramp Business Card",
        "category": "credit_card",
        "tier": "builder",
        "website": "https://ramp.com",
        "application_url": "https://ramp.com/sign-up",
        "product_type": "Corporate Charge Card",
        "credit_limit_min": 1000, "credit_limit_max": 1000000,
        "payment_terms": "monthly",
        "req_min_months_in_business": 0,
        "req_min_annual_revenue": 0,
        "req_min_personal_credit": 0,
        "req_min_bank_balance": 500,
        "req_ein": True,
        "req_business_checking": True,
        "ideal_bank_balance": 5000,
        "hard_pull": False,
        "requires_personal_guarantee": False,
        "reports_to_dnb": True, "reports_to_experian_biz": True,
        "automation_script": "generic",
        "approval_time": "1-2 days",
        "description": "No PG. 1.5% unlimited cashback. Bank balance determines limit. One of the easiest approvals.",
    },
    {
        "name": "Divvy (BILL Spend & Expense)",
        "category": "credit_card",
        "tier": "builder",
        "website": "https://getdivvy.com",
        "application_url": "https://getdivvy.com/get-started/",
        "product_type": "Corporate Card",
        "credit_limit_min": 500, "credit_limit_max": 500000,
        "payment_terms": "monthly",
        "req_min_months_in_business": 0,
        "req_min_annual_revenue": 0,
        "req_min_personal_credit": 0,
        "req_ein": True,
        "req_business_checking": True,
        "hard_pull": False,
        "requires_personal_guarantee": False,
        "reports_to_dnb": True,
        "automation_script": "generic",
        "approval_time": "Same day",
        "description": "No personal credit check. Spend management platform + credit. Good starter card.",
    },
    {
        "name": "Nav Business Financing",
        "category": "marketplace",
        "tier": "builder",
        "website": "https://www.nav.com",
        "application_url": "https://app.nav.com/register",
        "product_type": "Credit Monitoring + Marketplace",
        "credit_limit_min": 0, "credit_limit_max": 5000000,
        "payment_terms": "varies",
        "req_min_months_in_business": 0,
        "req_min_annual_revenue": 0,
        "req_min_personal_credit": 0,
        "req_ein": False,
        "hard_pull": False,
        "requires_personal_guarantee": False,
        "reports_to_dnb": False,
        "automation_script": "nav",
        "approval_time": "Instant signup",
        "description": "FREE business credit monitoring — see D&B PAYDEX, Experian Intelliscore + matched financing. Sign up first before anything else.",
        "notes": "This is primarily a credit monitoring tool. Sign up to track your scores and see matched loan offers.",
    },
    {
        "name": "Home Depot Commercial Account",
        "category": "net30",
        "tier": "builder",
        "website": "https://www.homedepot.com",
        "application_url": "https://www.homedepot.com/c/Commercial_Account",
        "product_type": "Commercial Revolving Charge",
        "credit_limit_min": 2000, "credit_limit_max": 55000,
        "payment_terms": "net30",
        "req_min_months_in_business": 0,
        "req_min_annual_revenue": 0,
        "req_min_personal_credit": 580,
        "req_ein": True,
        "ideal_min_personal_credit": 620,
        "hard_pull": True,
        "requires_personal_guarantee": True,
        "reports_to_dnb": True, "reports_to_experian_biz": True,
        "automation_script": "generic",
        "approval_time": "Instant - 7 days",
        "description": "Home Depot commercial account. Hard pull — apply after soft-pull cards established.",
    },
    {
        "name": "Sam's Club Business Mastercard",
        "category": "credit_card",
        "tier": "builder",
        "website": "https://www.samsclub.com",
        "application_url": "https://www.samsclub.com/content/credit-card/business-credit",
        "product_type": "Business Credit Card",
        "credit_limit_min": 1000, "credit_limit_max": 30000,
        "payment_terms": "monthly",
        "req_min_months_in_business": 0,
        "req_min_annual_revenue": 0,
        "req_min_personal_credit": 580,
        "req_ein": True,
        "ideal_min_personal_credit": 620,
        "hard_pull": True,
        "requires_personal_guarantee": True,
        "reports_to_dnb": True, "reports_to_experian_biz": True, "reports_to_equifax_biz": True,
        "automation_script": "generic",
        "approval_time": "Instant",
        "description": "5% cash back on gas. Reports to all 3 business bureaus.",
    },
    {
        "name": "Capital One Spark Classic",
        "category": "credit_card",
        "tier": "builder",
        "website": "https://www.capitalone.com",
        "application_url": "https://www.capitalone.com/small-business/credit-cards/spark-classic/",
        "product_type": "Business Credit Card",
        "credit_limit_min": 500, "credit_limit_max": 10000,
        "payment_terms": "monthly",
        "req_min_months_in_business": 0,
        "req_min_annual_revenue": 0,
        "req_min_personal_credit": 560,
        "req_ein": True,
        "ideal_min_personal_credit": 600,
        "hard_pull": True,
        "requires_personal_guarantee": True,
        "reports_to_dnb": True, "reports_to_experian_biz": True, "reports_to_equifax_biz": True,
        "automation_script": "generic",
        "approval_time": "Instant - 14 days",
        "description": "1% cashback. Easiest Capital One card to approve. No annual fee.",
    },
    # ══════════════════════════════════════════════════════════════════
    # TIER: ESTABLISHED — Major Business Credit Cards
    # Apply after 5+ tradelines, 6+ months
    # ══════════════════════════════════════════════════════════════════
    {
        "name": "Chase Ink Business Cash",
        "category": "credit_card",
        "tier": "established",
        "website": "https://creditcards.chase.com",
        "application_url": "https://creditcards.chase.com/business-credit-cards/ink/cash",
        "product_type": "Business Cash Back Credit Card",
        "credit_limit_min": 3000, "credit_limit_max": 25000,
        "interest_rate_min": 18.49, "interest_rate_max": 24.49,
        "payment_terms": "monthly",
        "req_min_months_in_business": 0,
        "req_min_annual_revenue": 0,
        "req_min_personal_credit": 660,
        "req_ein": True,
        "ideal_min_personal_credit": 700,
        "ideal_min_months": 12,
        "hard_pull": True,
        "requires_personal_guarantee": True,
        "reports_to_dnb": True, "reports_to_experian_biz": True, "reports_to_equifax_biz": True,
        "automation_script": "generic",
        "approval_time": "Instant - 14 days",
        "description": "5% on office/internet/cable (up to $25k). $750 signup bonus. No annual fee. Chase 5/24 rule applies.",
        "notes": "Chase 5/24: if you've opened 5+ personal cards in last 24 months, likely denied. Best to apply early in credit journey.",
    },
    {
        "name": "Chase Ink Business Unlimited",
        "category": "credit_card",
        "tier": "established",
        "website": "https://creditcards.chase.com",
        "application_url": "https://creditcards.chase.com/business-credit-cards/ink/unlimited",
        "product_type": "Business Credit Card",
        "credit_limit_min": 3000, "credit_limit_max": 25000,
        "payment_terms": "monthly",
        "req_min_months_in_business": 0,
        "req_min_annual_revenue": 0,
        "req_min_personal_credit": 660,
        "req_ein": True,
        "ideal_min_personal_credit": 700,
        "hard_pull": True,
        "requires_personal_guarantee": True,
        "reports_to_dnb": True, "reports_to_experian_biz": True,
        "automation_script": "generic",
        "approval_time": "Instant - 14 days",
        "description": "1.5% unlimited cashback. $750 signup bonus. No annual fee.",
    },
    {
        "name": "American Express Blue Business Cash",
        "category": "credit_card",
        "tier": "established",
        "website": "https://www.americanexpress.com",
        "application_url": "https://www.americanexpress.com/us/credit-cards/business/business-credit-cards/american-express-blue-business-cash-credit-card/",
        "product_type": "Business Credit Card",
        "credit_limit_min": 5000, "credit_limit_max": 50000,
        "interest_rate_min": 18.49, "interest_rate_max": 26.49,
        "payment_terms": "monthly",
        "req_min_months_in_business": 0,
        "req_min_annual_revenue": 0,
        "req_min_personal_credit": 640,
        "req_ein": True,
        "ideal_min_personal_credit": 680,
        "hard_pull": True,
        "requires_personal_guarantee": True,
        "reports_to_dnb": True, "reports_to_experian_biz": True,
        "automation_script": "generic",
        "approval_time": "Instant - 14 days",
        "description": "2% cashback on all purchases up to $50k/year. No annual fee.",
    },
    {
        "name": "American Express Business Gold",
        "category": "credit_card",
        "tier": "established",
        "website": "https://www.americanexpress.com",
        "application_url": "https://www.americanexpress.com/us/credit-cards/business/business-credit-cards/",
        "product_type": "Business Charge Card",
        "credit_limit_min": 5000, "credit_limit_max": 1000000,
        "payment_terms": "monthly",
        "req_min_months_in_business": 0,
        "req_min_annual_revenue": 0,
        "req_min_personal_credit": 660,
        "req_ein": True,
        "ideal_min_personal_credit": 700,
        "hard_pull": True,
        "requires_personal_guarantee": True,
        "reports_to_dnb": True, "reports_to_experian_biz": True,
        "automation_script": "generic",
        "approval_time": "Instant - 14 days",
        "description": "4x points on top 2 categories. No preset limit. $375/yr.",
    },
    {
        "name": "Capital One Venture X Business",
        "category": "credit_card",
        "tier": "established",
        "website": "https://www.capitalone.com",
        "application_url": "https://www.capitalone.com/small-business/credit-cards/venture-x/",
        "product_type": "Business Charge Card",
        "credit_limit_min": 5000, "credit_limit_max": 200000,
        "payment_terms": "monthly",
        "req_min_months_in_business": 0,
        "req_min_annual_revenue": 0,
        "req_min_personal_credit": 680,
        "req_ein": True,
        "ideal_min_personal_credit": 720,
        "hard_pull": True,
        "requires_personal_guarantee": True,
        "reports_to_dnb": True, "reports_to_experian_biz": True,
        "automation_script": "generic",
        "approval_time": "Instant - 14 days",
        "description": "10x on hotels/rental cars via Capital One Travel, 2x on everything else. $395/yr. Does NOT report to personal bureaus. Triple bureau pull at application — apply last.",
        "notes": "Capital One pulls all 3 personal bureaus. Always apply to Capital One LAST in any session.",
    },
    {
        "name": "Capital One Spark Cash Plus",
        "category": "credit_card",
        "tier": "established",
        "website": "https://www.capitalone.com",
        "application_url": "https://www.capitalone.com/small-business/credit-cards/spark-cash-plus/",
        "product_type": "Business Charge Card",
        "credit_limit_min": 3000, "credit_limit_max": 200000,
        "payment_terms": "monthly",
        "req_min_months_in_business": 0,
        "req_min_annual_revenue": 0,
        "req_min_personal_credit": 660,
        "req_ein": True,
        "ideal_min_personal_credit": 700,
        "hard_pull": True,
        "requires_personal_guarantee": True,
        "reports_to_dnb": True, "reports_to_experian_biz": True,
        "automation_script": "generic",
        "approval_time": "Instant - 14 days",
        "description": "2% unlimited cashback. $1200 signup bonus. No preset spending limit.",
    },
    {
        "name": "Bank of America Business Advantage",
        "category": "credit_card",
        "tier": "established",
        "website": "https://www.bankofamerica.com",
        "application_url": "https://www.bankofamerica.com/smallbusiness/credit-cards/",
        "product_type": "Business Credit Card",
        "credit_limit_min": 3000, "credit_limit_max": 50000,
        "payment_terms": "monthly",
        "req_min_months_in_business": 12,
        "req_min_annual_revenue": 0,
        "req_min_personal_credit": 660,
        "req_ein": True,
        "ideal_min_personal_credit": 700,
        "ideal_min_months": 24,
        "hard_pull": True,
        "requires_personal_guarantee": True,
        "reports_to_dnb": True,
        "automation_script": "generic",
        "approval_time": "Instant - 14 days",
        "description": "3% on chosen category. Preferred Rewards bonus multiplier.",
    },
    {
        "name": "US Bank Business Triple Cash",
        "category": "credit_card",
        "tier": "established",
        "website": "https://www.usbank.com",
        "application_url": "https://www.usbank.com/business-banking/business-credit-cards.html",
        "product_type": "Business Credit Card",
        "credit_limit_min": 2000, "credit_limit_max": 25000,
        "payment_terms": "monthly",
        "req_min_months_in_business": 0,
        "req_min_annual_revenue": 0,
        "req_min_personal_credit": 640,
        "req_ein": True,
        "ideal_min_personal_credit": 680,
        "hard_pull": True,
        "requires_personal_guarantee": True,
        "reports_to_dnb": True,
        "automation_script": "generic",
        "approval_time": "Instant - 14 days",
        "description": "3% on gas, office supply, cell phone. $500 signup bonus. No annual fee.",
    },
    {
        "name": "Chase Ink Business Preferred",
        "category": "credit_card",
        "tier": "established",
        "website": "https://creditcards.chase.com",
        "application_url": "https://creditcards.chase.com/business-credit-cards/ink/preferred",
        "product_type": "Business Travel Rewards Card",
        "credit_limit_min": 5000, "credit_limit_max": 100000,
        "payment_terms": "monthly",
        "req_min_months_in_business": 0,
        "req_min_annual_revenue": 0,
        "req_min_personal_credit": 680,
        "req_ein": True,
        "ideal_min_personal_credit": 720,
        "ideal_min_months": 12,
        "hard_pull": True,
        "requires_personal_guarantee": True,
        "reports_to_dnb": True, "reports_to_experian_biz": True,
        "automation_script": "generic",
        "approval_time": "Instant - 14 days",
        "description": "3x points on travel, shipping, internet/cable/phone. 100k signup bonus. $95/yr. Chase 5/24 rule applies.",
        "notes": "Chase 5/24 applies. Apply before other hard-pull cards.",
    },
    {
        "name": "American Express Business Platinum",
        "category": "credit_card",
        "tier": "established",
        "website": "https://www.americanexpress.com",
        "application_url": "https://www.americanexpress.com/us/credit-cards/business/business-credit-cards/american-express-business-platinum-card/",
        "product_type": "Business Charge Card",
        "credit_limit_min": 10000, "credit_limit_max": 1000000,
        "payment_terms": "monthly",
        "req_min_months_in_business": 12,
        "req_min_annual_revenue": 50000,
        "req_min_personal_credit": 680,
        "req_ein": True,
        "ideal_min_personal_credit": 720,
        "ideal_min_months": 24,
        "hard_pull": True,
        "requires_personal_guarantee": True,
        "reports_to_dnb": True, "reports_to_experian_biz": True,
        "automation_script": "generic",
        "approval_time": "Instant - 14 days",
        "description": "Premium travel card. 5x on flights/hotels. $695/yr. 120k+ signup bonus. No preset spending limit.",
    },
    {
        "name": "Bank of America Business Secured",
        "category": "credit_card",
        "tier": "builder",
        "website": "https://www.bankofamerica.com",
        "application_url": "https://www.bankofamerica.com/smallbusiness/credit-cards/secured-business-credit-card/",
        "product_type": "Secured Business Credit Card",
        "credit_limit_min": 1000, "credit_limit_max": 10000,
        "payment_terms": "monthly",
        "req_min_months_in_business": 0,
        "req_min_annual_revenue": 0,
        "req_min_personal_credit": 0,
        "req_ein": True,
        "req_business_checking": True,
        "hard_pull": True,
        "requires_personal_guarantee": True,
        "reports_to_dnb": True, "reports_to_experian_biz": True,
        "automation_script": "generic",
        "approval_time": "7-14 days",
        "description": "Secured card — deposit required equal to credit limit. Best for zero-credit-history businesses. Converts to unsecured after 12-18 months. 1.5% cashback.",
    },
    # ══════════════════════════════════════════════════════════════════
    # TIER: ADVANCED — Lines of Credit & Term Loans
    # ══════════════════════════════════════════════════════════════════
    {
        "name": "Headway Capital",
        "category": "line_of_credit",
        "tier": "advanced",
        "website": "https://www.headwaycapital.com",
        "application_url": "https://www.headwaycapital.com/apply/",
        "product_type": "Revolving Line of Credit",
        "credit_limit_min": 5000, "credit_limit_max": 100000,
        "interest_rate_min": 40.0, "interest_rate_max": 80.0,
        "payment_terms": "weekly",
        "req_min_months_in_business": 6,
        "req_min_annual_revenue": 50000,
        "req_min_personal_credit": 625,
        "req_ein": True,
        "req_business_checking": True,
        "ideal_min_months": 12,
        "ideal_min_revenue": 100000,
        "hard_pull": True,
        "requires_personal_guarantee": True,
        "reports_to_dnb": True,
        "automation_script": "generic",
        "approval_time": "Next business day",
        "description": "True revolving LOC. Only 6 months in business + $50K/yr revenue needed. Next-day funding. Good bridge to Bluevine.",
    },
    {
        "name": "Fundbox Line of Credit",
        "category": "line_of_credit",
        "tier": "advanced",
        "website": "https://fundbox.com",
        "application_url": "https://fundbox.com/apply/",
        "product_type": "Revolving Line of Credit",
        "credit_limit_min": 1000, "credit_limit_max": 150000,
        "interest_rate_min": 4.66, "interest_rate_max": 8.99,
        "payment_terms": "weekly",
        "req_min_months_in_business": 3,
        "req_min_annual_revenue": 25000,
        "req_min_personal_credit": 600,
        "req_ein": True,
        "req_business_checking": True,
        "ideal_min_months": 12,
        "ideal_min_revenue": 60000,
        "hard_pull": False,
        "requires_personal_guarantee": True,
        "reports_to_dnb": True,
        "automation_script": "fundbox",
        "approval_time": "Minutes",
        "description": "Only 3 months in business needed. Soft pull. Connect bank or accounting software. Best for newer businesses needing a LOC.",
    },
    {
        "name": "Bluevine Business Line of Credit",
        "category": "line_of_credit",
        "tier": "advanced",
        "website": "https://www.bluevine.com",
        "application_url": "https://app.bluevine.com/signup/line-of-credit",
        "product_type": "Revolving Line of Credit",
        "credit_limit_min": 6000, "credit_limit_max": 250000,
        "interest_rate_min": 6.2, "interest_rate_max": 78.0,
        "payment_terms": "weekly",
        "req_min_months_in_business": 24,
        "req_min_annual_revenue": 120000,
        "req_min_personal_credit": 625,
        "req_ein": True,
        "req_business_checking": True,
        "ideal_min_months": 36,
        "ideal_min_revenue": 240000,
        "hard_pull": True,
        "requires_personal_guarantee": True,
        "reports_to_dnb": True, "reports_to_experian_biz": True,
        "automation_script": "generic",
        "approval_time": "Same day",
        "description": "Revolving LOC. 2 year minimum. Funding same day on approval.",
    },
    {
        "name": "OnDeck Business Loan",
        "category": "loan",
        "tier": "advanced",
        "website": "https://www.ondeck.com",
        "application_url": "https://www.ondeck.com/apply",
        "product_type": "Term Loan",
        "credit_limit_min": 5000, "credit_limit_max": 250000,
        "interest_rate_min": 35.0, "interest_rate_max": 99.0,
        "payment_terms": "daily",
        "req_min_months_in_business": 12,
        "req_min_annual_revenue": 100000,
        "req_min_personal_credit": 600,
        "req_ein": True,
        "req_business_checking": True,
        "ideal_min_months": 24,
        "ideal_min_revenue": 200000,
        "hard_pull": True,
        "requires_personal_guarantee": True,
        "reports_to_dnb": True, "reports_to_experian_biz": True,
        "automation_script": "generic",
        "approval_time": "Same day",
        "description": "1 year minimum. Fast funding. Higher rates but accessible for businesses with revenue.",
    },
    {
        "name": "Lendio (Marketplace)",
        "category": "marketplace",
        "tier": "advanced",
        "website": "https://www.lendio.com",
        "application_url": "https://www.lendio.com/apply/",
        "product_type": "Loan Marketplace (75+ lenders)",
        "credit_limit_min": 1000, "credit_limit_max": 5000000,
        "payment_terms": "varies",
        "req_min_months_in_business": 6,
        "req_min_annual_revenue": 50000,
        "req_min_personal_credit": 560,
        "req_ein": True,
        "ideal_min_months": 24,
        "ideal_min_revenue": 120000,
        "hard_pull": True,
        "requires_personal_guarantee": True,
        "automation_script": "generic",
        "approval_time": "24-72 hours",
        "description": "One application reaches 75+ lenders. SBA, term, LOC, equipment. Best marketplace for established businesses.",
    },
    {
        "name": "National Funding",
        "category": "loan",
        "tier": "advanced",
        "website": "https://www.nationalfunding.com",
        "application_url": "https://www.nationalfunding.com/apply-now/",
        "product_type": "Term Loan / Equipment Financing",
        "credit_limit_min": 5000, "credit_limit_max": 500000,
        "interest_rate_min": 20.0, "interest_rate_max": 150.0,
        "payment_terms": "daily",
        "req_min_months_in_business": 6,
        "req_min_annual_revenue": 100000,
        "req_min_personal_credit": 575,
        "req_ein": True,
        "ideal_min_months": 24,
        "hard_pull": True,
        "requires_personal_guarantee": True,
        "reports_to_dnb": True,
        "automation_script": "generic",
        "approval_time": "24 hours",
        "description": "Flexible financing 6+ months. Also does equipment financing.",
    },
    # ══════════════════════════════════════════════════════════════════
    # TIER: PREMIUM — SBA Loans & Large Credit Lines
    # ══════════════════════════════════════════════════════════════════
    {
        "name": "SBA 7(a) Loan",
        "category": "sba",
        "tier": "premium",
        "website": "https://www.sba.gov",
        "application_url": "https://www.sba.gov/funding-programs/loans/7a-loans",
        "product_type": "SBA Government-Backed Loan",
        "credit_limit_min": 500, "credit_limit_max": 5000000,
        "interest_rate_min": 5.5, "interest_rate_max": 11.5,
        "payment_terms": "monthly",
        "req_min_months_in_business": 24,
        "req_min_annual_revenue": 0,
        "req_min_personal_credit": 650,
        "req_ein": True,
        "ideal_min_personal_credit": 700,
        "ideal_min_months": 36,
        "hard_pull": True,
        "requires_personal_guarantee": True,
        "reports_to_dnb": True, "reports_to_experian_biz": True,
        "auto_apply": False,
        "automation_script": "generic",
        "approval_time": "30-90 days",
        "description": "Best available rates. Up to $5M. 25-year terms for real estate. We prepare all documentation.",
        "notes": "Manual process — requires business plan, 3yr financials, tax returns. System prepares documents, human submits.",
    },
    {
        "name": "SBA Microloan",
        "category": "sba",
        "tier": "premium",
        "website": "https://www.sba.gov",
        "application_url": "https://www.sba.gov/funding-programs/loans/microloans",
        "product_type": "SBA Microloan",
        "credit_limit_min": 500, "credit_limit_max": 50000,
        "interest_rate_min": 6.5, "interest_rate_max": 13.0,
        "payment_terms": "monthly",
        "req_min_months_in_business": 0,
        "req_min_annual_revenue": 0,
        "req_min_personal_credit": 575,
        "req_ein": True,
        "hard_pull": True,
        "requires_personal_guarantee": True,
        "auto_apply": False,
        "automation_script": "generic",
        "approval_time": "30-60 days",
        "description": "Up to $50k for startups. Lower credit requirements. Through nonprofit intermediaries.",
    },
    {
        "name": "Funding Circle",
        "category": "loan",
        "tier": "premium",
        "website": "https://www.fundingcircle.com",
        "application_url": "https://www.fundingcircle.com/us/apply/",
        "product_type": "Term Loan",
        "credit_limit_min": 25000, "credit_limit_max": 500000,
        "interest_rate_min": 7.49, "interest_rate_max": 36.0,
        "payment_terms": "monthly",
        "req_min_months_in_business": 24,
        "req_min_annual_revenue": 50000,
        "req_min_personal_credit": 660,
        "req_ein": True,
        "req_business_checking": True,
        "ideal_min_months": 36,
        "ideal_min_revenue": 150000,
        "hard_pull": True,
        "requires_personal_guarantee": True,
        "reports_to_dnb": True,
        "automation_script": "generic",
        "approval_time": "1-3 days",
        "description": "Fixed-rate term loans. Good rates for established businesses.",
    },
]
